### PR TITLE
Update validation.md

### PR DESCRIPTION
**Pull request by r2d2rnd**
Changed command to get the CSR since the CSRs are not in a specified namespace

### CODE REVIEW

**Comment by r2d2rnd** [comment]
Changed command to get the CSRs since it shouldn't indicated the namespace for getting them

**Comment by r2d2rnd** [comment]
Hello @rdoxenham,

I believe that this could be approved if you agree and being merged in the documentation.

Best regards,
Oscar

**Comment by rdoxenham** [comment]
Sorry, @r2d2rnd - are you saying that there's no requirement to specify the namespace and that all csr's are not scoped resources?

**Comment by r2d2rnd** [comment]
Hello @rdoxenham,

Exactly that. It's a cluster resource, then, not needed to specify namespace as you can see here:

~~~
$ oc api-resources|grep csr
certificatesigningrequests            csr              certificates.k8s.io                   false        CertificateSigningReq
uest
~~~

Then, you can/should invoke then without using a namespace

**Comment by rdoxenham** [comment]
> Hello @rdoxenham,
> 
> Exactly that. It's a cluster resource, then, not needed to specify namespace as you can see here:
> 
> ```
> $ oc api-resources|grep csr
> certificatesigningrequests            csr              certificates.k8s.io                   false        CertificateSigningReq
> uest
> ```
> 
> Then, you can/should invoke then without using a namespace

In that case, thanks!

**Pull request merged**
